<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>PHP Developer</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h3>Parte 1</h3>
		<div><a href="ChangeString.php">Problema 1</a></div>
		<div><a href="CompleteRange.php">Problema 2</a></div>
		<div><a href="ClearPar.php">Problema 3</a></div>
		<h3>Parte 2</h3>
		<div>Problema Práctico</div>
    </body>
</html>
